### PR TITLE
Update useTracks.ts

### PR DESCRIPTION
**Pull request by FreitasAssis**
FIX error: Property 'getTrackPublications' does not exist on type 'Participant'.ts(2339)

### CODE REVIEW

**Comment by davidzhao** [comment]
this is expected. Components have been updated to work with livekit-client 2.0. Please reference the migration guide for details: https://docs.livekit.io/guides/migrate-from-v1/
